version: "3.8"

networks:
  api-network:
    driver: bridge

volumes:
  mysql-vol:

services:
  mysql_server:
    image: mysql:5.6
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_server
    ports:
      - "8080:8080"
    networks:
      - api-network
